language: php

php:
  - 7.1

before_script:
  - composer install --ignore-platform-reqs
  - composer update --ignore-platform-reqs

notifications:
  notifications:
    email:
      on_success: always
      on_failure: always