language: php

php:
  - 7.1.9

before_script:
  - composer install --no-interaction --no-dev --prefer-dist
  - composer self-update --2

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  notifications:
    email:
      on_success: always
      on_failure: always