language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer install --ignore-platform-reqs
  - composer update --ignore-platform-reqs

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  notifications:
    email:
      on_success: always
      on_failure: always