language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install --prefer-dist --no-interaction --no-dev
  - composer install --ignore-platform-reqs
  - composer update --ignore-platform-reqs

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  notifications:
    email:
      on_success: always
      on_failure: always