language: php

php:
  - 7.3
  - 7.4
  - 7.5
  - 7.6
  - 7.7
  - 7.8
  - 7.9
  - 8.0

before_script:
  - composer install --ignore-platform-reqs
  - composer update --ignore-platform-reqs

notifications:
  notifications:
    email:
      on_success: always
      on_failure: always